name: debug
on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
jobs:
  debug:
    runs-on: ${{ github.event.inputs.runs-on }}
    steps:
      - uses: mxschmitt/action-tmate@v3
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}
          retention-days: 7
          compression-level: 0
