name: run
on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
      shell:
        type: choice
        options:
          - bash
          - pwsh
      run:
        required: true
jobs:
  run:
    runs-on: ${{ github.event.inputs.runs-on }}
    steps:
      - shell: ${{ github.event.inputs.shell }}
        run: ${{ github.event.inputs.run }}
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}
          retention-days: 7
          compression-level: 0
